name: Deploy

on:
  push:
    branches: [ deploy ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          persist-credentials: false

    - name: Deploy
      run: |
        npm install
        npm run build
        npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod

    # - name: Deploy
    #   uses: JamesIves/github-pages-deploy-action@releases/v3
    #   with:
    #     ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
    #     BRANCH: master
    #     FOLDER: public
